import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.testng.annotations.Test;
import java.time.Duration;
import java.util.List;

public class SauceDemoPractice1Test {
    @Test
    public void SauceDemoPractice1() {
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--start-maximized");
        options.addArguments("--incognito");
        options.addArguments("--disable-notfications");
        WebDriver driver = new ChromeDriver(options);
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
        driver.get("https://www.saucedemo.com/");
        WebElement loginInput = driver.findElement(By.xpath("//input[@data-test='username']"));
        loginInput.click();
        loginInput.sendKeys("standard_user");
        WebElement passwordInput = driver.findElement(By.xpath("//input[@data-test='password']"));
        passwordInput.click();
        passwordInput.sendKeys("secret_sauce");
        WebElement loginButton = driver.findElement(By.xpath("//input[@data-test='login-button']"));
        loginButton.click();
        List<WebElement> linkToBriefcase = driver.findElements(By.id("item_4_img_link"));
        boolean isPresentElementBriefcase = !linkToBriefcase.isEmpty();
        System.out.println("1) Поиск по ID элемента 'Рюкзак' выполнен. Элемент присутствует на странице: " + isPresentElementBriefcase);
        List<WebElement> buttonAddToCart = driver.findElements(By.name("add-to-cart-sauce-labs-backpack"));
        boolean isPresentElementButtonAddToCart = !buttonAddToCart.isEmpty();
        System.out.println("2) Поиск первой кнопки 'AddToCart' по имени элемента 'AddToCart' (напротив рюкзака) выполнен. Элемент присутствует на странице: " + isPresentElementButtonAddToCart);
        List<WebElement> headerContainer = driver.findElements(By.className("header_container"));
        boolean isPresentElementHeaderContainer = !headerContainer.isEmpty();
        System.out.print("3) Поиск шапки сайта по классу элемента 'HeaderContainer' выполнен. Элемент присутствует на странице: " + isPresentElementHeaderContainer);
        List<WebElement> tagNameButtonAddToCart2 = driver.findElements(By.tagName("button"));
        if (tagNameButtonAddToCart2.size() >= 2) {
            WebElement secondElementTagNameButtonAddToCart2 = tagNameButtonAddToCart2.get(1);
            System.out.println(secondElementTagNameButtonAddToCart2.getText());
        }
        boolean isPresentElementButtonAddToCart2 = !tagNameButtonAddToCart2.isEmpty();
        System.out.println("4) Поиск второй кнопки 'AddToCart' по наименованию тега 'Button' выполнен. Элемент присутствует на странице: " + isPresentElementButtonAddToCart2);
        WebElement menu = driver.findElement(By.id("react-burger-menu-btn"));
        menu.click();
        List<WebElement> allItems = driver.findElements(By.linkText("All Items"));
        boolean isPresentElementAllItems = !allItems.isEmpty();
        System.out.println("5) Поиск элемента 'All Items' по полному тексту ссылки 'All Items' выполнен. Элемент присутствует на странице: " + isPresentElementAllItems);
        List<WebElement> resetAppState = driver.findElements(By.partialLinkText("App State"));
        boolean isPresentElementResetAppState = !resetAppState.isEmpty();
        System.out.println("6) Поиск элемента 'Reset App State' по частичному совпадению текста ссылки 'App State' выполнен. Элемент присутствует на странице: " + isPresentElementResetAppState);
        List<WebElement> about = driver.findElements(By.xpath("//a[@data-test='about-sidebar-link']"));
        boolean isPresentElementAbout = !about.isEmpty();
        System.out.println("7) Поиск элемента 'About' по Xpath (Тег --> Атрибут = Значение) выполнен. Элемент присутствует на странице: " + isPresentElementAbout);
        List<WebElement> logout = driver.findElements(By.xpath("//a[text()='Logout']"));
        boolean isPresentElementLogout = !logout.isEmpty();
        System.out.println("8) Поиск элемента 'Logout' по Xpath (Тег --> Текст = Значение) выполнен. Элемент присутствует на странице: " + isPresentElementLogout);
        List<WebElement> closeMenu = driver.findElements(By.xpath("//button[contains(@id,'react-burger-cross-')]"));
        boolean isPresentElementCloseMenu = !closeMenu.isEmpty();
        System.out.println("9) Поиск элемента 'CloseMenu' по Xpath (Тег --> Атрибут = Частичное совпадение значения) выполнен. Элемент присутствует на странице: " + isPresentElementCloseMenu);
        WebElement buttonCloseMenu = driver.findElement(By.id("react-burger-cross-btn"));
        buttonCloseMenu.click();
        List<WebElement> descriptionOfTheBackpack = driver.findElements(By.xpath("//div[contains(text(),'with the sleek, streamlined Sly Pack that melds uncompromising style with unequaled laptop and tablet protection')]"));
        boolean isPresentElementDescriptionOfTheBackpack = !descriptionOfTheBackpack.isEmpty();
        System.out.println("10) Поиск текста (описание рюкзака) по частичному совпадению текста по Xpath выполнен. Элемент присутствует на странице: " + isPresentElementDescriptionOfTheBackpack);
        List<WebElement> firstDiv = driver.findElements(By.xpath("//button[@id='react-burger-menu-btn']//ancestor::div"));
        boolean isPresentElementFirstDivButton = !firstDiv.isEmpty();
        System.out.println("11) Поиск первого родительского тега div, содержащего кнопку 'Open Menu' через Xpath ancestor выполнен. Элемент присутствует на странице: " + isPresentElementFirstDivButton);
        List<WebElement> buttonOpenMenu = driver.findElements(By.xpath("//div[@id='root']//descendant::button"));
        boolean isPresentElementFirstButtonInDiv = !buttonOpenMenu.isEmpty();
        System.out.println("12) Поиск кнопки 'Open Menu' от первого родительского тега div, через Xpath descendant выполнен. Элемент присутствует на странице: " + isPresentElementFirstButtonInDiv);
        List<WebElement> buttonAddToCart1 = driver.findElements(By.xpath("//div[@data-test='inventory-item-name']/following::button"));
        boolean isPresentElementButtonAddToCart1 = !buttonAddToCart1.isEmpty();
        System.out.println("13) Поиск первой кнопки 'AddToCart' от родительского тега div, через Xpath following выполнен. Элемент присутствует на странице: " + isPresentElementButtonAddToCart1);
        List<WebElement> divContainingSpan = driver.findElements (By.xpath("//span[text()='Products']/parent::div"));
        boolean isPresentElementDivSpan = !divContainingSpan.isEmpty();
        System.out.println("14) Поиск родительского тега div элемента span через Xpath parent выполнен. Элемент присутствует на странице: " + isPresentElementDivSpan);
        List<WebElement> divContainingSpanClassSelectContainer = driver.findElements (By.xpath("//span[@class='select_container']/preceding::div[1]"));
        boolean isPresentElementDivContainingSpanClassSelectContainer = !divContainingSpanClassSelectContainer.isEmpty();
        System.out.println("15) Поиск крайнего элемента div в DOM, содержащего тег span имеющего класс 'select_container' через Xpath preceding выполнен. Элемент присутствует на странице: " + isPresentElementDivContainingSpanClassSelectContainer);
        List<WebElement> imgMoto = driver.findElements (By.xpath("//img[@alt='Sauce Labs Bike Light' and @class='inventory_item_img']"));
        boolean isPresentElementImgMoto = !imgMoto.isEmpty();
        System.out.println("16) Поиск картинки с мотоциклом через Xpath с условием AND выполнен. Элемент присутствует на странице: " + isPresentElementImgMoto);
        List<WebElement> firstDivClassInventoryItemImg = driver.findElements (By.cssSelector(".inventory_item_img"));
        boolean isPresentElementFirstDivClassInventoryItemImg = !firstDivClassInventoryItemImg.isEmpty();
        System.out.println("17) Поиск первого тега div через CSS селектор '.class' с классом 'inventory_item_img' выполнен. Элемент присутствует на странице: " + isPresentElementFirstDivClassInventoryItemImg);
        List<WebElement> firstButtonAddToCart = driver.findElements (By.cssSelector(".btn_primary.btn_inventory"));
        boolean isPresentElementFirstButtonAddToCart = !firstButtonAddToCart.isEmpty();
        System.out.println("18) Поиск первой кнопки 'Add to cart' через CSS селектор '.class.class' с несколькими классами: 'btn_primary' и 'btn_inventory' выполнен. Элемент присутствует на странице: " + isPresentElementFirstButtonAddToCart);
        List<WebElement> firstDivPrice = driver.findElements (By.cssSelector(".inventory_item .inventory_item_price"));
        boolean isPresentElementFirstDivPrice = !firstDivPrice.isEmpty();
        System.out.println("19) Поиск вложенного тега div с атрибутом class = 'inventory_item_price' в теге div с атрибутом class = 'inventory_item' через CSS селектор '.class .class' выполнен. Элемент присутствует на странице: " + isPresentElementFirstDivPrice);
        List<WebElement> sauceLabsBackpack = driver.findElements (By.cssSelector("#item_4_title_link"));
        boolean isPresentElementSauceLabsBackpack = !sauceLabsBackpack.isEmpty();
        System.out.println("20) Поиск элемента 'Sauce Labs Backpack' через CSS селектор '#id' выполнен. Элемент присутствует на странице: " + isPresentElementSauceLabsBackpack);
        List<WebElement> cssTagFooter = driver.findElements (By.cssSelector("#item_4_title_link"));
        boolean isPresentElementFooter = !cssTagFooter.isEmpty();
        System.out.println("21) Поиск через CSS селектор по тегу 'footer' выполнен. Элемент присутствует на странице: " + isPresentElementFooter);
        List<WebElement> cssClassDivBasket = driver.findElements (By.cssSelector("div.shopping_cart_container"));
        boolean isPresentElementDivBasket = !cssClassDivBasket.isEmpty();
        System.out.println("22) Поиск через CSS селектор по классу 'shopping_cart_container' тега 'div' выполнен. Элемент присутствует на странице: " + isPresentElementDivBasket);
        List<WebElement> cssAttrDivInventoryContainer = driver.findElements (By.cssSelector("div[data-test='inventory-container']"));
        boolean isPresentElementDivInventoryContainer = !cssAttrDivInventoryContainer.isEmpty();
        System.out.println("23) Поиск тега div CSS селектор по по атрибуту 'data-test' и значению 'inventory-container' выполнен. Элемент присутствует на странице: " + isPresentElementDivInventoryContainer);
        List<WebElement> cssButtonAttrAddToCart = driver.findElements (By.cssSelector("button[class~='btn_primary']"));
        boolean isPresentElementButtonAttrAddToCart = !cssButtonAttrAddToCart.isEmpty();
        System.out.println("24) Поиск первой кнопки 'Add to cart' CSS селектор по частичному совпадению значения атрибута 'class' выполнен. Элемент присутствует на странице: " + isPresentElementButtonAttrAddToCart);
        List<WebElement> cssDivDataTestInventory = driver.findElements (By.cssSelector("div[data-test|='inventory']"));
        boolean isPresentElementDivDataTestInventory= !cssDivDataTestInventory.isEmpty();
        System.out.println("25) Поиск первого тега div через CSS селектор атрибута 'data-test', который начинается с 'inventory' выполнен. Элемент присутствует на странице: " + isPresentElementDivDataTestInventory);
        List<WebElement> cssButtonDataTestAddToCart = driver.findElements (By.cssSelector("button[data-test^='add-to-cart']"));
        boolean isPresentElementButtonDataTestAddToCart = !cssButtonDataTestAddToCart.isEmpty();
        System.out.println("26) Поиск первой кнопки 'Add to cart' через CSS селектор по значению атрибута 'data-test', который начинается с 'add-to-cart' выполнен. Элемент присутствует на странице: " + isPresentElementButtonDataTestAddToCart);
        List<WebElement> cssImgBackpack = driver.findElements (By.cssSelector("button[data-test$='sauce-labs-backpack']"));
        boolean isPresentElementImgBackpack = !cssImgBackpack.isEmpty();
        System.out.println("27) Поиск картинки с рюкзаком через CSS селектор по значению атрибута 'data-test', который заканчивается на 'sauce-labs-backpack' выполнен. Элемент присутствует на странице: " + isPresentElementImgBackpack);
        List<WebElement> cssButtonDataTestAddToCart2 = driver.findElements (By.cssSelector("button[data-test*='to-cart-sauce-labs-bike']"));
        boolean isPresentElementButtonDataTestAddToCart2 = !cssButtonDataTestAddToCart2.isEmpty();
        System.out.println("28) Поиск второй кнопки 'Add to cart' через CSS селектор по значению атрибута 'data-test', который содержит в себе 'to-cart-sauce-labs-bike' выполнен. Элемент присутствует на странице: " + isPresentElementButtonDataTestAddToCart2);
        driver.quit();
    }
}
